steps:
  - label: "Run Build Script"
    command: 
      - export MYPAT=$(buildkite-agent secret get KEY_PAT)
      - echo $$MYPAT
      - git clone "https://jmishra.c:$$MYPAT@spruce.arlo.com/apps/ios.git"


  - label: "Set Environment Variables"
    command:
      - export SIMULATOR_BUILD="${SIMULATOR_BUILD:-false}"
      - export ENABLE_TA="${ENABLE_TA:-true}"
      - export BUILD_TIME_STAMP=$(date +%s)
      - export ARTIFACTORY_CREDS="jenkins-artifactory-creds"

  - label: "Pre-Build Step"
    command:
      - echo "Starting Pre-Build Step"
      - |
        if [ -z "$APP_VERSION" ]; then 
          echo "Default version ${DEFAULT_APP_VERSION} will be used"; 
        else 
          echo "Using provided version ${APP_VERSION}"; 
        fi

  - group: "Parallel Builds"
    steps:
      - label: "Unit Tests"
        command:
          - |
            if [ "$REQUIRED_UNIT_TEST" = true ]; then
              ./build-wrapper-macosx-x86/build-wrapper-macosx-x86 --out-dir bw_output ./build.sh UnitTest
            else
              echo "Skipping Unit Test"
            fi

      - label: "Development Build"
        command:
          - export ENVIRONMENT="Development"
          - export ARCHIVE_NAME="${BRANCH_NAME}-${ENVIRONMENT}_${NEW_BUILD_NUMBER}"
          - export RELEASE_VERSION="${APP_VERSION}"
          - "./build.sh ${ENVIRONMENT} ${RELEASE_VERSION} ${ARCHIVE_NAME} ${NEW_BUILD_NUMBER}"
          - cp build_app_template.plist "build/Release-iphoneos/${ARCHIVE_NAME}.plist"
          - |
            /usr/libexec/PlistBuddy -c "Set :items:0:assets:0:url https://arloios:<ARTIFACTORY_CREDS>@artifactory.arlocloud.com/artifactory/hmsios-local/${ARCHIVE_NAME}.ipa" "build/Release-iphoneos/${ARCHIVE_NAME}.plist"
